In [0]:
# some libraries
import pandas as pd
import numpy as np

In [2]:
from numpy.random import seed
seed(1)
from tensorflow import set_random_seed
set_random_seed(2)

In [3]:
from google.colab import files
uploaded = files.upload()

Saving chn_series.csv to chn_series.csv


In [9]:
# to read the dataframe
import io
df = pd.read_csv(io.StringIO(uploaded['chn_series.csv'].decode('utf-8')))
df

Date  CHN_TM_TAX_MRCH_BR_ZS  ...  CHN_TM_TAX_MANF_BR_ZS   CPI
0   2001-12-31                  10.02  ...                   9.64  35.0
1   2002-12-31                  10.00  ...                   9.63  35.0
2   2003-12-31                  10.00  ...                   9.63  34.0
3   2004-12-31                  10.00  ...                   9.63  34.0
4   2005-12-31                  10.00  ...                   9.63  32.0
5   2006-12-31                  10.00  ...                   9.63  33.0
6   2007-12-31                   9.94  ...                   9.55  35.0
7   2008-12-31                   9.94  ...                   9.55  36.0
8   2009-12-31                   9.94  ...                   9.55  36.0
9   2010-12-31                   9.94  ...                   9.55  35.0
10  2011-12-31                   9.94  ...                   9.55  36.0
11  2014-12-31                   9.98  ...                   9.51  36.0
12  2015-12-31                   9.98  ...                   9.51  37.0
13  2016-12-31                   9.98  ...                   9.51  40.0

[14 rows x 928 columns]

In [0]:
import datetime
def datetiem(x):
    date_time_obj = datetime.datetime.strptime(x, '%Y-%m-%d' )
    return date_time_obj

In [0]:
df["Date"] = df["Date"].apply(lambda x: datetiem(x))
df.index = df.Date # index as date because time is not a variable
df=df.drop(['Date'], axis=1)

In [12]:
# df0 = df.fillna(0)
# removes columns where more than 30% of data is missing
# rationale for 0.7, if we can train test split for 0.7/ 0.3 we can accept at least 70% filled data
# fills remaining missing values with the mean of the column   
df_mean = df.loc[:, pd.notnull(df).sum()>len(df)*.80].fillna(df.mean())
# df_mean = df.loc[:, pd.notnull(df).sum()>len(df)*.70].fillna(df.interpolate())
df_mean

CHN_TM_TAX_MRCH_BR_ZS  ...   CPI
Date                               ...      
2001-12-31                  10.02  ...  35.0
2002-12-31                  10.00  ...  35.0
2003-12-31                  10.00  ...  34.0
2004-12-31                  10.00  ...  34.0
2005-12-31                  10.00  ...  32.0
2006-12-31                  10.00  ...  33.0
2007-12-31                   9.94  ...  35.0
2008-12-31                   9.94  ...  36.0
2009-12-31                   9.94  ...  36.0
2010-12-31                   9.94  ...  35.0
2011-12-31                   9.94  ...  36.0
2014-12-31                   9.98  ...  36.0
2015-12-31                   9.98  ...  37.0
2016-12-31                   9.98  ...  40.0

[14 rows x 649 columns]

In [0]:
CPI_list = list(df_mean.CPI)
def pct_df(df):
    df.drop(["CPI"], axis=1)
    new_df = df.pct_change()
    new_df.replace(np.nan, 0)
    new_df = new_df.replace([np.inf, -np.inf], 0)
    new_df = new_df.dropna(how='all')
    new_df['CPI']=CPI_list[1:]
    new_df = new_df.fillna(df.mean())
    return new_df
def UpsampleByTimeIndex(df,bytime,method):
    upsampled = df.resample(bytime)
    interpolated = upsampled.interpolate(method=method)
    return interpolated
# Ignore the index and treat the values as equally space
# ‘nearest’, ‘zero’, ‘slinear’, ‘quadratic’, ‘cubic’, ‘spline’, ‘barycentric’, ‘polynomial’
# .agg aggregates/ groups by specified time frame
# D for days, M for months
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html 
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.interpolate.html 
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.resample.Resampler.aggregate.html 
# https://machinelearningmastery.com/resample-interpolate-time-series-data-python/

In [0]:
pct_df_mean = pct_df(df_mean)

In [0]:
#Ignore this code; helper functions for binarizing
# list_col_names = list(pct_df_mean.columns.values)
from itertools import repeat
def binarize(x):
    if x< 0:
        x = -1
    elif x>0:
        x=1
    else:
        x = 0
    return x
month_cpi = [x for item in CPI_list[1:len(CPI_list)-1] for x in repeat(item, 12)]
month_cpi.insert(len(a),CPI_list[len(CPI_list)-1])
def bin_action_cpi(df):
    df.drop(["CPI"], axis=1)
    df = df.applymap(binarize)
    try:
        df['CPI']=CPI_list[1:]
    except:
        df['CPI']= month_cpi
    return df
def bin_action(df):
    df = df.applymap(binarize)
    return df
def binarize10(x):
    if x<= 0:
        x = 0
    else:
        x = 1
    return x
def bin_action_cpi10(df):
    df.drop(["CPI"], axis=1)
    df = df.applymap(binarize10)
    try:
        df['CPI']=CPI_list[1:]
    except:
        df['CPI']= month_cpi
    return df
def bin_action10(df):
    df = df.applymap(binarize10)
    return df
def binarize123(x):
    if x< 0:
        x = 1
    elif x>0:
        x=3
    else:
        x = 2
    return x
def bin_action_cpi123(df):
    df.drop(["CPI"], axis=1)
    df = df.applymap(binarize123)
    try:
        df['CPI']=CPI_list[1:]
    except:
        df['CPI']= month_cpi
    return df
def bin_action123(df):
    df = df.applymap(binarize123)
    return df

NameError: ignored

In [0]:
# percentage change df and binarize 123
# df_mean_wo_cpi = pct_df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
# df_latest = UpsampleByTimeIndex(pct_df_mean,'Y','linear')
# df_latest = bin_action_cpi123(df_latest)
# df_latest.index = list(range(len(df_latest)))
# df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'Y','linear')
# df_latest_wo_cpi = bin_action123(df_latest_wo_cpi)
# df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

# percentage change df and binarize 0,1
# df_mean_wo_cpi = pct_df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
# df_latest = UpsampleByTimeIndex(pct_df_mean,'M','linear')
# df_latest = bin_action_cpi10(df_latest)
# df_latest.index = list(range(len(df_latest)))
# df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'M','linear')
# df_latest_wo_cpi = bin_action10(df_latest_wo_cpi)
# df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

# percentage change df and binarize -1,0,1
# df_mean_wo_cpi = pct_df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
# df_latest = UpsampleByTimeIndex(pct_df_mean,'Y','linear')
# df_latest = bin_action_cpi(df_latest)
# df_latest.index = list(range(len(df_latest)))
# df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'Y','linear')
# df_latest_wo_cpi = bin_action(df_latest_wo_cpi)
# df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

# percentage change df
df_mean_wo_cpi = pct_df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
df_latest = UpsampleByTimeIndex(pct_df_mean,'M','linear')
df_latest.index = list(range(len(df_latest)))
df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'M','linear')
df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

# mean df
# df_mean_wo_cpi = df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
# df_latest = UpsampleByTimeIndex(df_mean,'Y','linear')
# df_latest.index = list(range(len(df_latest)))
# df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'Y','linear')
# df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

In [16]:
df_latest_wo_cpi

CHN_TM_TAX_MRCH_BR_ZS  ...  CHN_TM_TAX_MANF_BR_ZS
0                -0.001996  ...              -0.001037
1                -0.001830  ...              -0.000951
2                -0.001663  ...              -0.000864
3                -0.001497  ...              -0.000778
4                -0.001331  ...              -0.000692
..                     ...  ...                    ...
164               0.000000  ...               0.000000
165               0.000000  ...               0.000000
166               0.000000  ...               0.000000
167               0.000000  ...               0.000000
168               0.000000  ...               0.000000

[169 rows x 648 columns]

In [17]:
# check for null, if false then no missing values
def null_check(dfr):
    return dfr.isnull().values.any()
# print(null_check(df0))
# print(null_check(df_mean))
print(null_check(df_latest_wo_cpi))

False


In [18]:
from sklearn.preprocessing import MinMaxScaler
sc= MinMaxScaler(feature_range=(0,1))

input_data = df_latest.values
test_data = df_latest_wo_cpi.values
input_data[:,0:len(input_data[0])-1] = sc.fit_transform(input_data[:,0:len(input_data[0])-1])
test_data[:,0:len(test_data[0])] = sc.fit_transform(test_data[:,:])
test_data

array([[0.39943477, 0.        , 0.24698996, ..., 0.3130883 , 0.        ,
        0.87512967],
       [0.41602811, 0.02969421, 0.29809305, ..., 0.30728131, 0.00288664,
        0.88553553],
       [0.43262144, 0.05938843, 0.34919614, ..., 0.30147431, 0.00577329,
        0.89594139],
       ...,
       [0.5985548 , 0.35633055, 0.28456818, ..., 0.08617954, 0.85512137,
        1.        ],
       [0.5985548 , 0.35633055, 0.25321678, ..., 0.04308977, 0.92756068,
        1.        ],
       [0.5985548 , 0.35633055, 0.22186537, ..., 0.        , 1.        ,
        1.        ]])

In [19]:
print(test_data.shape)
print(input_data.shape) # check data and shape, are there 22/ 229 rows?

(169, 648)
(169, 649)


In [20]:
df_latest.head()

CHN_TM_TAX_MRCH_BR_ZS  ...        CPI
0               0.399435  ...  35.000000
1               0.416028  ...  34.916667
2               0.432621  ...  34.833333
3               0.449215  ...  34.750000
4               0.465808  ...  34.666667

[5 rows x 649 columns]

In [21]:
n_steps = 3
df_test=test_data[-n_steps:]
CPI_test = df_latest['CPI'][-n_steps:]
print(CPI_test)
print(df_test.shape)
input_feature = input_data[:len(input_data)-n_steps] # to remove last 5 rows, follow the time step you set

166    39.50
167    39.75
168    40.00
Name: CPI, dtype: float64
(3, 648)


In [22]:
input_feature.shape # check shape 

(166, 649)

In [0]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [24]:
# choose a number of time steps
from numpy import array
# convert into input/output
X, y = split_sequences(input_feature, n_steps)
print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])
# the array is (Total number of samples, time step, total number of dimensions)

(164, 3, 648) (164,)
[[0.39943477 0.         0.24698996 ... 0.3130883  0.         0.87512967]
 [0.41602811 0.02969421 0.29809305 ... 0.30728131 0.00288664 0.88553553]
 [0.43262144 0.05938843 0.34919614 ... 0.30147431 0.00577329 0.89594139]] 34.833333333333336
[[0.41602811 0.02969421 0.29809305 ... 0.30728131 0.00288664 0.88553553]
 [0.43262144 0.05938843 0.34919614 ... 0.30147431 0.00577329 0.89594139]
 [0.44921478 0.08908264 0.40029923 ... 0.29566732 0.00865993 0.90634725]] 34.75
[[0.43262144 0.05938843 0.34919614 ... 0.30147431 0.00577329 0.89594139]
 [0.44921478 0.08908264 0.40029923 ... 0.29566732 0.00865993 0.90634725]
 [0.46580811 0.11877685 0.45140232 ... 0.28986033 0.01154658 0.91675311]] 34.666666666666664
[[0.44921478 0.08908264 0.40029923 ... 0.29566732 0.00865993 0.90634725]
 [0.46580811 0.11877685 0.45140232 ... 0.28986033 0.01154658 0.91675311]
 [0.48240145 0.14847106 0.50250541 ... 0.28405333 0.01443322 0.92715897]] 34.583333333333336
[[0.46580811 0.11877685 0.45140232 .

In [0]:
# final model
# https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/ 
# refer to this if necessary
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, X.shape[2])))
model.add(Dense(15))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# model.save_weights('my_model_weights.h5')

In [32]:
# fit model
model.fit(X, y, epochs=200, verbose=0)#, validation_split=0.2, batch_size=5)

In [0]:
# demonstrate prediction
x_input = df_test
x_input = x_input.reshape((1, n_steps,X.shape[2] ))
yhat = model.predict(x_input, verbose=0)

Percentage Error

In [34]:
print(yhat)
actual = CPI_test[len(df_latest)-1]
print(float((abs(actual-yhat)/actual)*100))

[[40.06353]]
0.15882492065429688


In [35]:
weight_tensors = model.layers[1].weights
weight_names = list(map(lambda x: x.name, weight_tensors))
print(weight_names)

['dense_3/kernel:0', 'dense_3/bias:0']


In [36]:
for layer in model.layers:
        if "LSTM" in str(layer):
            weightLSTM = layer.get_weights()
warr,uarr, barr = weightLSTM
print(warr.shape) # warr is a numpy array of weights for inputs
print(uarr.shape) # uarr is a numpy array of weights for hidden units
print(barr.shape) # barr is a numpy array of bias

(648, 200)
(50, 200)
(200,)


In [0]:
print(warr)
print(uarr) 
print(barr) 

[[-0.05996489  0.00334863 -0.07000631 ... -0.08312024 -0.05508691
   0.06340362]
 [ 0.03778417 -0.01975109  0.05824827 ... -0.0331271   0.00853069
  -0.05852728]
 [ 0.04641208  0.01114873 -0.03798164 ...  0.05747066 -0.04485274
   0.0443713 ]
 ...
 [ 0.05347044 -0.0572511   0.04036112 ... -0.02875088  0.05896998
  -0.07833659]
 [ 0.01239917  0.08323803 -0.01764604 ... -0.03914334 -0.06543626
  -0.01121462]
 [ 0.03294032  0.07181647  0.02700024 ... -0.00603995 -0.00806883
  -0.04849005]]
[[ 0.12589791 -0.07054115 -0.08861891 ... -0.03676573  0.05221381
  -0.15633503]
 [ 0.13306502 -0.12319936 -0.05175697 ...  0.02289279  0.04650595
  -0.06229677]
 [-0.13476533  0.02517678 -0.00739818 ... -0.06426033 -0.00743123
  -0.00591115]
 ...
 [ 0.01102621  0.00032036 -0.04485288 ...  0.12112253 -0.02007239
  -0.02193324]
 [-0.02039579  0.03089585 -0.00102132 ... -0.05920744 -0.02224196
   0.06074055]
 [-0.02116491 -0.0589334   0.04262791 ... -0.05624822 -0.01637447
  -0.04362038]]
[-2.03319232e-05

In [0]:
# change df to percentage changes
# play with the rank/ totaln
# interpolate lesser 
# time step

In [0]:
time step = 5, CPI, indicator data
interpolate by year, 22 data points
# 20.441774368286133
interpolate by month, 262 DP
# 1.0591048002243042
interpolate by day, 7920 DP
# 0.015229816548526287 

After performing percentage change and normalizing 
interpolate by year time step 7
# 0.6501209735870361
# 351430.6875
interpolate by year time step 5
# 0.5464288592338562
# 320606.21875
interpolate by year time step 3
# 1.6997615098953247
interpolate by month time step 7
# 1.4450266361236572
interpolate by month time step 5
# 0.217756450176239


*** champion ***
interpolate by month time step 3
# 0.4332916736602783 25 units
# 0.15020249783992767 50 units 0.24396678805351257
# 0.08212704956531525 75 units
# 0.025785423815250397 75 units dense 15 , 1
# 0.09989678114652634 75 units dense 25 , 1
***  winner  # 0.016958503052592278 75 units dense 35 , 1 
*** end ***


binarize -1,0,1
year time step = 7
# 63.047935485839844
year time step = 5
# 59.16572189331055
year time step = 3
# 82.13848114013672
month time step = 7
# 11.621817588806152
month time step = 5
# 11.747268676757812
month time step = 3
# 15.268765449523926


binarize 0,1
year time step = 7
# 1.3483071327209473
year time step = 5
# 2.037656784057617
year time step = 3
# 4.179565906524658
month time step = 7
# 0.44504478573799133
month time step = 5
# 4.9152421951293945
month time step = 3
# 3.9173173904418945

binarize 1,2,3
year time step = 7
# 5.180117607116699
year time step = 5
# 4.566781520843506
year time step = 3
# 1.8392828702926636
month time step = 7
# 3.652085065841675
month time step = 5
# 4.432069778442383
month time step = 3
# 0.7650640606880188