In [0]:
# some libraries
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving nga_series.csv to nga_series.csv


In [3]:
# to read the dataframe
import io
df = pd.read_csv(io.StringIO(uploaded['nga_series.csv'].decode('utf-8')))
df

Date  NGA_TM_TAX_MANF_BR_ZS  ...  NGA_TM_TAX_TCOM_BR_ZS   CPI
0   1995-12-31                  68.44  ...                 146.76   6.9
1   1996-12-31                  67.44  ...                 146.82   6.9
2   1997-12-31                  67.44  ...                 146.82  17.6
3   1998-12-31                  67.44  ...                 146.82  19.0
4   1999-12-31                  67.44  ...                 146.82  16.0
5   2000-12-31                  67.44  ...                 146.82  12.0
6   2001-12-31                  67.44  ...                 146.82  10.0
7   2002-12-31                  67.44  ...                 146.82  16.0
8   2003-12-31                  67.44  ...                 146.82  14.0
9   2005-12-31                  64.57  ...                 146.85  19.0
10  2006-12-31                  64.57  ...                 146.85  22.0
11  2008-12-31                  64.57  ...                 146.85  27.0
12  2009-12-31                  59.84  ...                 146.91  25.0
13  2010-12-31                  59.84  ...                 146.91  24.0
14  2011-12-31                  59.84  ...                 146.91  24.0
15  2013-12-31                  59.84  ...                 146.91  25.0
16  2014-12-31                  59.84  ...                 146.91  27.0
17  2015-12-31                  60.44  ...                 146.82  26.0
18  2016-12-31                  60.44  ...                 146.82  28.0

[19 rows x 1021 columns]

In [0]:
import datetime
def datetiem(x):
    date_time_obj = datetime.datetime.strptime(x, '%Y-%m-%d' )
    return date_time_obj

In [0]:
df["Date"] = df["Date"].apply(lambda x: datetiem(x))
df.index = df.Date # index as date because time is not a variable
df=df.drop(['Date'], axis=1)

In [25]:
# df0 = df.fillna(0)
# removes columns where more than 30% of data is missing
# rationale for 0.7, if we can train test split for 0.7/ 0.3 we can accept at least 70% filled data
# fills remaining missing values with the mean of the column   
df_mean = df.loc[:, pd.notnull(df).sum()>len(df)*.85].fillna(df.mean())
# df_mean = df.loc[:, pd.notnull(df).sum()>len(df)*.70].fillna(df.interpolate())
df_mean

NGA_TM_TAX_MANF_BR_ZS  ...   CPI
Date                               ...      
1995-12-31                  68.44  ...   6.9
1996-12-31                  67.44  ...   6.9
1997-12-31                  67.44  ...  17.6
1998-12-31                  67.44  ...  19.0
1999-12-31                  67.44  ...  16.0
2000-12-31                  67.44  ...  12.0
2001-12-31                  67.44  ...  10.0
2002-12-31                  67.44  ...  16.0
2003-12-31                  67.44  ...  14.0
2005-12-31                  64.57  ...  19.0
2006-12-31                  64.57  ...  22.0
2008-12-31                  64.57  ...  27.0
2009-12-31                  59.84  ...  25.0
2010-12-31                  59.84  ...  24.0
2011-12-31                  59.84  ...  24.0
2013-12-31                  59.84  ...  25.0
2014-12-31                  59.84  ...  27.0
2015-12-31                  60.44  ...  26.0
2016-12-31                  60.44  ...  28.0

[19 rows x 583 columns]

In [0]:
CPI_list = list(df_mean.CPI)
def pct_df(df):
    df.drop(["CPI"], axis=1)
    new_df = df.pct_change()
    new_df.replace(np.nan, 0)
    new_df = new_df.replace([np.inf, -np.inf], 0)
    new_df = new_df.dropna(how='all')
    new_df['CPI']=CPI_list[1:]
    new_df = new_df.fillna(df.mean())
    return new_df
def UpsampleByTimeIndex(df,bytime,method):
    upsampled = df.resample(bytime)
    interpolated = upsampled.interpolate(method=method)
    return interpolated
# Ignore the index and treat the values as equally space
# ‘nearest’, ‘zero’, ‘slinear’, ‘quadratic’, ‘cubic’, ‘spline’, ‘barycentric’, ‘polynomial’
# .agg aggregates/ groups by specified time frame
# D for days, M for months
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html 
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.interpolate.html 
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.resample.Resampler.aggregate.html 
# https://machinelearningmastery.com/resample-interpolate-time-series-data-python/

In [0]:
pct_df_mean = pct_df(df_mean)

In [10]:
#Ignore this code; helper functions for binarizing
# list_col_names = list(pct_df_mean.columns.values)
from itertools import repeat
def binarize(x):
    if x< 0:
        x = -1
    elif x>0:
        x=1
    else:
        x = 0
    return x
month_cpi = [x for item in CPI_list[1:len(CPI_list)-1] for x in repeat(item, 12)]
month_cpi.insert(len(a),CPI_list[len(CPI_list)-1])
def bin_action_cpi(df):
    df.drop(["CPI"], axis=1)
    df = df.applymap(binarize)
    try:
        df['CPI']=CPI_list[1:]
    except:
        df['CPI']= month_cpi
    return df
def bin_action(df):
    df = df.applymap(binarize)
    return df
def binarize10(x):
    if x<= 0:
        x = 0
    else:
        x = 1
    return x
def bin_action_cpi10(df):
    df.drop(["CPI"], axis=1)
    df = df.applymap(binarize10)
    try:
        df['CPI']=CPI_list[1:]
    except:
        df['CPI']= month_cpi
    return df
def bin_action10(df):
    df = df.applymap(binarize10)
    return df
def binarize123(x):
    if x< 0:
        x = 1
    elif x>0:
        x=3
    else:
        x = 2
    return x
def bin_action_cpi123(df):
    df.drop(["CPI"], axis=1)
    df = df.applymap(binarize123)
    try:
        df['CPI']=CPI_list[1:]
    except:
        df['CPI']= month_cpi
    return df
def bin_action123(df):
    df = df.applymap(binarize123)
    return df

NameError: ignored

In [0]:
# percentage change df and binarize 123
# df_mean_wo_cpi = pct_df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
# df_latest = UpsampleByTimeIndex(pct_df_mean,'Y','linear')
# df_latest = bin_action_cpi123(df_latest)
# df_latest.index = list(range(len(df_latest)))
# df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'Y','linear')
# df_latest_wo_cpi = bin_action123(df_latest_wo_cpi)
# df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

# percentage change df and binarize 0,1
# df_mean_wo_cpi = pct_df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
# df_latest = UpsampleByTimeIndex(pct_df_mean,'M','linear')
# df_latest = bin_action_cpi10(df_latest)
# df_latest.index = list(range(len(df_latest)))
# df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'M','linear')
# df_latest_wo_cpi = bin_action10(df_latest_wo_cpi)
# df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

# percentage change df and binarize -1,0,1
# df_mean_wo_cpi = pct_df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
# df_latest = UpsampleByTimeIndex(pct_df_mean,'Y','linear')
# df_latest = bin_action_cpi(df_latest)
# df_latest.index = list(range(len(df_latest)))
# df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'Y','linear')
# df_latest_wo_cpi = bin_action(df_latest_wo_cpi)
# df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

# percentage change df
df_mean_wo_cpi = pct_df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
df_latest = UpsampleByTimeIndex(pct_df_mean,'M','linear')
df_latest.index = list(range(len(df_latest)))
df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'M','linear')
df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

# mean df
# df_mean_wo_cpi = df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
# df_latest = UpsampleByTimeIndex(df_mean,'Y','linear')
# df_latest.index = list(range(len(df_latest)))
# df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'Y','linear')
# df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

In [29]:
df_latest_wo_cpi

NGA_TM_TAX_MANF_BR_ZS  ...  NGA_TM_TAX_TCOM_BR_ZS
0                -0.014611  ...               0.000409
1                -0.013394  ...               0.000375
2                -0.012176  ...               0.000341
3                -0.010959  ...               0.000307
4                -0.009741  ...               0.000273
..                     ...  ...                    ...
236               0.003342  ...              -0.000204
237               0.002507  ...              -0.000153
238               0.001671  ...              -0.000102
239               0.000836  ...              -0.000051
240               0.000000  ...               0.000000

[241 rows x 582 columns]

In [30]:
# check for null, if false then no missing values
def null_check(dfr):
    return dfr.isnull().values.any()
# print(null_check(df0))
# print(null_check(df_mean))
print(null_check(df_latest_wo_cpi))

False


In [31]:
from sklearn.preprocessing import MinMaxScaler
sc= MinMaxScaler(feature_range=(0,1))

input_data = df_latest.values
test_data = df_latest_wo_cpi.values
input_data[:,0:len(input_data[0])-1] = sc.fit_transform(input_data[:,0:len(input_data[0])-1])
test_data[:,0:len(test_data[0])] = sc.fit_transform(test_data[:,:])
test_data

array([[0.70415577, 0.        , 0.15185556, ..., 1.        , 0.95768026,
        1.        ],
       [0.71877637, 0.00727355, 0.15556226, ..., 0.97277166, 0.95988668,
        0.96664623],
       [0.73339696, 0.01454711, 0.15926895, ..., 0.94554332, 0.96209309,
        0.93329247],
       ...,
       [0.8996691 , 0.21943233, 0.85129588, ..., 0.56104994, 0.35776505,
        0.49979567],
       [0.88963601, 0.15335749, 0.92564794, ..., 0.61715493, 0.35477213,
        0.54977523],
       [0.87960292, 0.08728266, 1.        , ..., 0.67325992, 0.3517792 ,
        0.5997548 ]])

In [15]:
print(test_data.shape)
print(input_data.shape) # check data and shape, are there 22/ 229 rows?

(241, 609)
(241, 610)


In [16]:
df_latest.head()

NGA_TM_TAX_MANF_BR_ZS  ...        CPI
0               0.704156  ...   6.900000
1               0.718776  ...   7.791667
2               0.733397  ...   8.683333
3               0.748018  ...   9.575000
4               0.762638  ...  10.466667

[5 rows x 610 columns]

In [32]:
n_steps = 3
df_test=test_data[-n_steps:]
CPI_test = df_latest['CPI'][-n_steps:]
print(CPI_test)
print(df_test.shape)
input_feature = input_data[:len(input_data)-n_steps] # to remove last 5 rows, follow the time step you set

238    27.666667
239    27.833333
240    28.000000
Name: CPI, dtype: float64
(3, 582)


In [18]:
input_feature.shape # check shape 

(238, 610)

In [0]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [34]:
# choose a number of time steps
from numpy import array
# convert into input/output
X, y = split_sequences(input_feature, n_steps)
print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])
# the array is (Total number of samples, time step, total number of dimensions)

(236, 3, 582) (236,)
[[0.70415577 0.         0.15185556 ... 1.         0.95768026 1.        ]
 [0.71877637 0.00727355 0.15556226 ... 0.97277166 0.95988668 0.96664623]
 [0.73339696 0.01454711 0.15926895 ... 0.94554332 0.96209309 0.93329247]] 8.683333333333334
[[0.71877637 0.00727355 0.15556226 ... 0.97277166 0.95988668 0.96664623]
 [0.73339696 0.01454711 0.15926895 ... 0.94554332 0.96209309 0.93329247]
 [0.74801756 0.02182066 0.16297565 ... 0.91831498 0.96429951 0.8999387 ]] 9.575000000000001
[[0.73339696 0.01454711 0.15926895 ... 0.94554332 0.96209309 0.93329247]
 [0.74801756 0.02182066 0.16297565 ... 0.91831498 0.96429951 0.8999387 ]
 [0.76263815 0.02909422 0.16668234 ... 0.89108664 0.96650592 0.86658493]] 10.466666666666667
[[0.74801756 0.02182066 0.16297565 ... 0.91831498 0.96429951 0.8999387 ]
 [0.76263815 0.02909422 0.16668234 ... 0.89108664 0.96650592 0.86658493]
 [0.77725875 0.03636777 0.17038904 ... 0.8638583  0.96871234 0.83323117]] 11.358333333333334
[[0.76263815 0.02909422 0

In [0]:
# final model
# https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/ 
# refer to this if necessary
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
model = Sequential()
model.add(LSTM(75, activation='relu', input_shape=(n_steps, X.shape[2])))
model.add(Dense(15))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# model.save_weights('my_model_weights.h5')

In [36]:
# fit model
model.fit(X, y, epochs=200, verbose=0)#, validation_split=0.2, batch_size=5)

In [0]:
# demonstrate prediction
x_input = df_test
x_input = x_input.reshape((1, n_steps,X.shape[2] ))
yhat = model.predict(x_input, verbose=0)

Percentage Error

In [38]:
print(yhat)
actual = CPI_test[len(df_latest)-1]
print(float((abs(actual-yhat)/actual)*100))

[[28.0054]]
0.019284656271338463


In [39]:
weight_tensors = model.layers[1].weights
weight_names = list(map(lambda x: x.name, weight_tensors))
print(weight_names)

['dense_3/kernel:0', 'dense_3/bias:0']


In [40]:
for layer in model.layers:
        if "LSTM" in str(layer):
            weightLSTM = layer.get_weights()
warr,uarr, barr = weightLSTM
print(warr.shape) # warr is a numpy array of weights for inputs
print(uarr.shape) # uarr is a numpy array of weights for hidden units
print(barr.shape) # barr is a numpy array of bias

(582, 300)
(75, 300)
(300,)


In [41]:
print(warr)
print(uarr)
print(barr)

[[ 0.03749638 -0.02997526 -0.04632678 ... -0.00324335 -0.07669651
   0.0438001 ]
 [ 0.04962246 -0.06883258  0.02367057 ...  0.09105638 -0.023903
   0.01684958]
 [-0.03012713 -0.04754846 -0.01662874 ...  0.07281887 -0.03872166
  -0.02841193]
 ...
 [-0.06825925  0.04132728  0.07908301 ... -0.00705177 -0.08011845
   0.00313503]
 [-0.0440183  -0.0308653  -0.03427765 ... -0.08223053 -0.08163113
  -0.06002896]
 [ 0.00381582 -0.08496253  0.04720399 ... -0.03476831 -0.07972182
  -0.09328835]]
[[-0.07719569  0.07363452  0.0602853  ... -0.03115223 -0.08237154
   0.09580831]
 [ 0.05686579  0.02484708 -0.01817427 ... -0.03467558 -0.04065197
   0.02562957]
 [ 0.08081912 -0.02479234 -0.01371005 ...  0.04565225 -0.01285446
  -0.00993495]
 ...
 [ 0.01473714 -0.05161301 -0.03240162 ... -0.03766557 -0.04943531
   0.10727484]
 [ 0.05498635 -0.07392467 -0.02696898 ...  0.00527024 -0.0207024
   0.0723711 ]
 [ 0.02927645  0.09873219  0.07743395 ...  0.03289894 -0.0679174
  -0.02810632]]
[ 1.22587280e-02 -5.

In [0]:
# change df to percentage changes
# play with the rank/ totaln
# interpolate lesser 
# time step

In [0]:
time step = 5, CPI, indicator data
interpolate by year, 22 data points
# 20.441774368286133
interpolate by month, 262 DP
# 1.0591048002243042
interpolate by day, 7920 DP
# 0.015229816548526287 

After performing percentage change and normalizing 
interpolate by year time step 7
# 0.6501209735870361
# 351430.6875
interpolate by year time step 5
# 0.5464288592338562
# 320606.21875
interpolate by year time step 3
# 1.6997615098953247
interpolate by month time step 7
# 1.4450266361236572
interpolate by month time step 5
# 0.217756450176239


*** champion ***
interpolate by month time step 3
# 0.4332916736602783 25 units
# 0.15020249783992767 50 units 0.24396678805351257
# 0.08212704956531525 75 units
# 0.025785423815250397 75 units dense 15 , 1
# 0.09989678114652634 75 units dense 25 , 1
***  winner  # 0.016958503052592278 75 units dense 35 , 1 
*** end ***


binarize -1,0,1
year time step = 7
# 63.047935485839844
year time step = 5
# 59.16572189331055
year time step = 3
# 82.13848114013672
month time step = 7
# 11.621817588806152
month time step = 5
# 11.747268676757812
month time step = 3
# 15.268765449523926


binarize 0,1
year time step = 7
# 1.3483071327209473
year time step = 5
# 2.037656784057617
year time step = 3
# 4.179565906524658
month time step = 7
# 0.44504478573799133
month time step = 5
# 4.9152421951293945
month time step = 3
# 3.9173173904418945

binarize 1,2,3
year time step = 7
# 5.180117607116699
year time step = 5
# 4.566781520843506
year time step = 3
# 1.8392828702926636
month time step = 7
# 3.652085065841675
month time step = 5
# 4.432069778442383
month time step = 3
# 0.7650640606880188