In [0]:
# some libraries
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving sgp_series.csv to sgp_series.csv


In [3]:
# to read the dataframe
import io
df = pd.read_csv(io.StringIO(uploaded['sgp_series.csv'].decode('utf-8')))
df

Date  SGP_TM_TAX_MANF_BR_ZS  ...    CPI  CPI_
0   31/12/1995                   5.56  ...   9.26     3
1   31/12/1996                   5.56  ...   8.80     7
2   31/12/1997                   5.56  ...   8.66     9
3   31/12/1998                   5.56  ...   9.10     7
4   31/12/1999                   5.56  ...   9.10     7
5   31/12/2000                   5.56  ...   9.10     6
6   31/12/2001                   5.56  ...   9.20     4
7   31/12/2002                   5.56  ...   9.30     5
8   31/12/2003                   5.56  ...   9.40     5
9   31/12/2004                   5.56  ...   9.30     5
10  31/12/2005                   5.56  ...   9.40     5
11  31/12/2006                   5.56  ...   9.40     5
12  31/12/2007                   7.09  ...   9.30     4
13  31/12/2008                   7.23  ...   9.20     4
14  31/12/2009                   7.20  ...   9.20     3
15  31/12/2010                   7.18  ...   9.30     1
16  31/12/2011                   7.13  ...   9.20     5
17  31/12/2012                   7.14  ...  87.00     5
18  31/12/2013                   7.12  ...  86.00     3
19  31/12/2014                   7.15  ...  84.00     7
20  31/12/2015                   5.74  ...  85.00     7
21  31/12/2016                   5.74  ...  84.00     7

[22 rows x 882 columns]

In [0]:
import datetime
def datetiem(x):
    date_time_obj = datetime.datetime.strptime(x, '%d/%m/%Y' )
    return date_time_obj

In [0]:
df["Date"] = df["Date"].apply(lambda x: datetiem(x))
df.index = df.Date # index as date because time is not a variable
df=df.drop(['Date','CPI_'], axis=1)

In [9]:
# df0 = df.fillna(0)
# removes columns where more than 30% of data is missing
# rationale for 0.7, if we can train test split for 0.7/ 0.3 we can accept at least 70% filled data
# fills remaining missing values with the mean of the column   
df_mean = df.loc[:, pd.notnull(df).sum()>len(df)*.70].fillna(df.mean())
# df_mean = df.loc[:, pd.notnull(df).sum()>len(df)*.70].fillna(df.interpolate())
df_mean

SGP_TM_TAX_MANF_BR_ZS  ...    CPI
Date                               ...       
1995-12-31                   5.56  ...   9.26
1996-12-31                   5.56  ...   8.80
1997-12-31                   5.56  ...   8.66
1998-12-31                   5.56  ...   9.10
1999-12-31                   5.56  ...   9.10
2000-12-31                   5.56  ...   9.10
2001-12-31                   5.56  ...   9.20
2002-12-31                   5.56  ...   9.30
2003-12-31                   5.56  ...   9.40
2004-12-31                   5.56  ...   9.30
2005-12-31                   5.56  ...   9.40
2006-12-31                   5.56  ...   9.40
2007-12-31                   7.09  ...   9.30
2008-12-31                   7.23  ...   9.20
2009-12-31                   7.20  ...   9.20
2010-12-31                   7.18  ...   9.30
2011-12-31                   7.13  ...   9.20
2012-12-31                   7.14  ...  87.00
2013-12-31                   7.12  ...  86.00
2014-12-31                   7.15  ...  84.00
2015-12-31                   5.74  ...  85.00
2016-12-31                   5.74  ...  84.00

[22 rows x 582 columns]

In [0]:
CPI_list = list(df_mean.CPI)
def pct_df(df):
    df.drop(["CPI"], axis=1)
    new_df = df.pct_change()
    new_df.replace(np.nan, 0)
    new_df = new_df.replace([np.inf, -np.inf], 0)
    new_df = new_df.dropna(how='all')
    new_df['CPI']=CPI_list[1:]
    new_df = new_df.fillna(df.mean())
    return new_df
def UpsampleByTimeIndex(df,bytime,method):
    upsampled = df.resample(bytime)
    interpolated = upsampled.interpolate(method=method)
    return interpolated
# Ignore the index and treat the values as equally space
# ‘nearest’, ‘zero’, ‘slinear’, ‘quadratic’, ‘cubic’, ‘spline’, ‘barycentric’, ‘polynomial’
# .agg aggregates/ groups by specified time frame
# D for days, M for months
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html 
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.interpolate.html 
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.resample.Resampler.aggregate.html 
# https://machinelearningmastery.com/resample-interpolate-time-series-data-python/

In [0]:
pct_df_mean = pct_df(df_mean)

In [0]:
#Ignore this code; helper functions for binarizing
# list_col_names = list(pct_df_mean.columns.values)
from itertools import repeat
def binarize(x):
    if x< 0:
        x = -1
    elif x>0:
        x=1
    else:
        x = 0
    return x
month_cpi = [x for item in CPI_list[1:len(CPI_list)-1] for x in repeat(item, 12)]
month_cpi.insert(len(a),CPI_list[len(CPI_list)-1])
def bin_action_cpi(df):
    df.drop(["CPI"], axis=1)
    df = df.applymap(binarize)
    try:
        df['CPI']=CPI_list[1:]
    except:
        df['CPI']= month_cpi
    return df
def bin_action(df):
    df = df.applymap(binarize)
    return df
def binarize10(x):
    if x<= 0:
        x = 0
    else:
        x = 1
    return x
def bin_action_cpi10(df):
    df.drop(["CPI"], axis=1)
    df = df.applymap(binarize10)
    try:
        df['CPI']=CPI_list[1:]
    except:
        df['CPI']= month_cpi
    return df
def bin_action10(df):
    df = df.applymap(binarize10)
    return df
def binarize123(x):
    if x< 0:
        x = 1
    elif x>0:
        x=3
    else:
        x = 2
    return x
def bin_action_cpi123(df):
    df.drop(["CPI"], axis=1)
    df = df.applymap(binarize123)
    try:
        df['CPI']=CPI_list[1:]
    except:
        df['CPI']= month_cpi
    return df
def bin_action123(df):
    df = df.applymap(binarize123)
    return df

In [0]:
# percentage change df and binarize 123
# df_mean_wo_cpi = pct_df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
# df_latest = UpsampleByTimeIndex(pct_df_mean,'Y','linear')
# df_latest = bin_action_cpi123(df_latest)
# df_latest.index = list(range(len(df_latest)))
# df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'Y','linear')
# df_latest_wo_cpi = bin_action123(df_latest_wo_cpi)
# df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

# percentage change df and binarize 0,1
# df_mean_wo_cpi = pct_df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
# df_latest = UpsampleByTimeIndex(pct_df_mean,'M','linear')
# df_latest = bin_action_cpi10(df_latest)
# df_latest.index = list(range(len(df_latest)))
# df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'M','linear')
# df_latest_wo_cpi = bin_action10(df_latest_wo_cpi)
# df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

# percentage change df and binarize -1,0,1
# df_mean_wo_cpi = pct_df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
# df_latest = UpsampleByTimeIndex(pct_df_mean,'Y','linear')
# df_latest = bin_action_cpi(df_latest)
# df_latest.index = list(range(len(df_latest)))
# df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'Y','linear')
# df_latest_wo_cpi = bin_action(df_latest_wo_cpi)
# df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

# percentage change df
df_mean_wo_cpi = pct_df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
df_latest = UpsampleByTimeIndex(pct_df_mean,'M','linear')
df_latest.index = list(range(len(df_latest)))
df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'M','linear')
df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

# mean df
# df_mean_wo_cpi = df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
# df_latest = UpsampleByTimeIndex(df_mean,'Y','linear')
# df_latest.index = list(range(len(df_latest)))
# df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'Y','linear')
# df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

In [13]:
df_latest_wo_cpi

SGP_TM_TAX_MANF_BR_ZS  ...  SGP_TM_TAX_MRCH_BR_ZS
0                 0.000000  ...              -0.003035
1                 0.000000  ...              -0.002782
2                 0.000000  ...              -0.002529
3                 0.000000  ...              -0.002276
4                 0.000000  ...              -0.002023
..                     ...  ...                    ...
236              -0.065734  ...              -0.148208
237              -0.049301  ...              -0.111156
238              -0.032867  ...              -0.074104
239              -0.016434  ...              -0.037052
240               0.000000  ...               0.000000

[241 rows x 581 columns]

In [14]:
# check for null, if false then no missing values
def null_check(dfr):
    return dfr.isnull().values.any()
# print(null_check(df0))
# print(null_check(df_mean))
print(null_check(df_latest_wo_cpi))

False


In [15]:
from sklearn.preprocessing import MinMaxScaler
sc= MinMaxScaler(feature_range=(0,1))

input_data = df_latest.values
test_data = df_latest_wo_cpi.values
input_data[:,0:len(input_data[0])-1] = sc.fit_transform(input_data[:,0:len(input_data[0])-1])
test_data[:,0:len(test_data[0])] = sc.fit_transform(test_data[:,:])
test_data

array([[0.4174641 , 0.25219423, 0.28784186, ..., 0.54088922, 0.49924887,
        0.33803899],
       [0.4174641 , 0.25234104, 0.28811868, ..., 0.53275056, 0.49924887,
        0.33823259],
       [0.4174641 , 0.25248785, 0.28839551, ..., 0.52461191, 0.49924887,
        0.33842619],
       ...,
       [0.34788675, 0.21162996, 0.35648138, ..., 0.53211954, 0.47142937,
        0.28363518],
       [0.38267542, 0.23279296, 0.37319031, ..., 0.52385642, 0.48533912,
        0.3119987 ],
       [0.4174641 , 0.25395595, 0.38989924, ..., 0.51559331, 0.49924887,
        0.34036222]])

In [16]:
print(test_data.shape)
print(input_data.shape) # check data and shape, are there 22/ 229 rows?

(241, 581)
(241, 582)


In [17]:
df_latest.head()

SGP_TM_TAX_MANF_BR_ZS  ...       CPI
0               0.417464  ...  8.800000
1               0.417464  ...  8.788333
2               0.417464  ...  8.776667
3               0.417464  ...  8.765000
4               0.417464  ...  8.753333

[5 rows x 582 columns]

In [18]:
n_steps = 3
df_test=test_data[-n_steps:]
CPI_test = df_latest['CPI'][-n_steps:]
print(CPI_test)
print(df_test.shape)
input_feature = input_data[:len(input_data)-n_steps] # to remove last 5 rows, follow the time step you set

238    84.166667
239    84.083333
240    84.000000
Name: CPI, dtype: float64
(3, 581)


In [19]:
input_feature.shape # check shape 

(238, 582)

In [0]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [21]:
# choose a number of time steps
from numpy import array
# convert into input/output
X, y = split_sequences(input_feature, n_steps)
print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])
# the array is (Total number of samples, time step, total number of dimensions)

(236, 3, 581) (236,)
[[0.4174641  0.25219423 0.28784186 ... 0.54088922 0.49924887 0.33803899]
 [0.4174641  0.25234104 0.28811868 ... 0.53275056 0.49924887 0.33823259]
 [0.4174641  0.25248785 0.28839551 ... 0.52461191 0.49924887 0.33842619]] 8.776666666666667
[[0.4174641  0.25234104 0.28811868 ... 0.53275056 0.49924887 0.33823259]
 [0.4174641  0.25248785 0.28839551 ... 0.52461191 0.49924887 0.33842619]
 [0.4174641  0.25263466 0.28867233 ... 0.51647326 0.49924887 0.33861979]] 8.765
[[0.4174641  0.25248785 0.28839551 ... 0.52461191 0.49924887 0.33842619]
 [0.4174641  0.25263466 0.28867233 ... 0.51647326 0.49924887 0.33861979]
 [0.4174641  0.25278147 0.28894916 ... 0.50833461 0.49924887 0.3388134 ]] 8.753333333333334
[[0.4174641  0.25263466 0.28867233 ... 0.51647326 0.49924887 0.33861979]
 [0.4174641  0.25278147 0.28894916 ... 0.50833461 0.49924887 0.3388134 ]
 [0.4174641  0.25292828 0.28922598 ... 0.50019595 0.49924887 0.339007  ]] 8.741666666666667
[[0.4174641  0.25278147 0.28894916 ... 

In [22]:
# final model
# https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/ 
# refer to this if necessary
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
model = Sequential()
model.add(LSTM(75, activation='relu', input_shape=(n_steps, X.shape[2])))
model.add(Dense(15))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# model.save_weights('my_model_weights.h5')

Using TensorFlow backend.


In [23]:
# fit model
model.fit(X, y, epochs=200, verbose=0)#, validation_split=0.2, batch_size=5)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where










In [0]:
# demonstrate prediction
x_input = df_test
x_input = x_input.reshape((1, n_steps,X.shape[2] ))
yhat = model.predict(x_input, verbose=0)

Percentage Error

In [25]:
print(yhat)
actual = CPI_test[len(df_latest)-1]
print(float((abs(actual-yhat)/actual)*100))

[[83.593376]]
0.48407599329948425


In [0]:
weight_tensors = model.layers[1].weights
weight_names = list(map(lambda x: x.name, weight_tensors))
print(weight_names)

['dense_10/kernel:0', 'dense_10/bias:0']


In [0]:
for layer in model.layers:
        if "LSTM" in str(layer):
            weightLSTM = layer.get_weights()
warr,uarr, barr = weightLSTM
print(warr.shape) # warr is a numpy array of weights for inputs
print(uarr.shape) # uarr is a numpy array of weights for hidden units
print(barr.shape) # barr is a numpy array of bias

(674, 300)
(75, 300)
(300,)


In [0]:
print(warr)
print(uarr)
print(barr)

In [0]:
# change df to percentage changes
# play with the rank/ totaln
# interpolate lesser 
# time step

In [0]:
time step = 5, CPI, indicator data
interpolate by year, 22 data points
# 20.441774368286133
interpolate by month, 262 DP
# 1.0591048002243042
interpolate by day, 7920 DP
# 0.015229816548526287 

After performing percentage change and normalizing 
interpolate by year time step 7
# 0.6501209735870361
# 351430.6875
interpolate by year time step 5
# 0.5464288592338562
# 320606.21875
interpolate by year time step 3
# 1.6997615098953247
interpolate by month time step 7
# 1.4450266361236572
interpolate by month time step 5
# 0.217756450176239


*** champion ***
interpolate by month time step 3
# 0.4332916736602783 25 units
# 0.15020249783992767 50 units 0.24396678805351257
# 0.08212704956531525 75 units
# 0.025785423815250397 75 units dense 15 , 1
# 0.09989678114652634 75 units dense 25 , 1
***  winner  # 0.016958503052592278 75 units dense 35 , 1 
*** end ***


binarize -1,0,1
year time step = 7
# 63.047935485839844
year time step = 5
# 59.16572189331055
year time step = 3
# 82.13848114013672
month time step = 7
# 11.621817588806152
month time step = 5
# 11.747268676757812
month time step = 3
# 15.268765449523926


binarize 0,1
year time step = 7
# 1.3483071327209473
year time step = 5
# 2.037656784057617
year time step = 3
# 4.179565906524658
month time step = 7
# 0.44504478573799133
month time step = 5
# 4.9152421951293945
month time step = 3
# 3.9173173904418945

binarize 1,2,3
year time step = 7
# 5.180117607116699
year time step = 5
# 4.566781520843506
year time step = 3
# 1.8392828702926636
month time step = 7
# 3.652085065841675
month time step = 5
# 4.432069778442383
month time step = 3
# 0.7650640606880188