In [0]:
# some libraries
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving isr_series.csv to isr_series.csv


In [4]:
# to read the dataframe
import io
df = pd.read_csv(io.StringIO(uploaded['isr_series.csv'].decode('utf-8')))
df

Date  ISR_TM_TAX_MANF_BR_ZS  ...  ISR_TM_TAX_TCOM_BR_ZS   CPI
0   1999-12-31                  13.43  ...                  49.97  68.0
1   2000-12-31                  13.43  ...                  49.97  66.0
2   2001-12-31                  13.48  ...                  49.96  76.0
3   2002-12-31                  11.30  ...                  49.83  73.0
4   2003-12-31                  11.27  ...                  49.79  70.0
5   2004-12-31                  11.28  ...                  49.75  64.0
6   2005-12-31                  11.27  ...                  49.74  63.0
7   2006-12-31                  11.26  ...                  49.73  59.0
8   2007-12-31                  11.26  ...                  49.04  61.0
9   2008-12-31                  11.28  ...                  50.08  60.0
10  2009-12-31                  11.29  ...                  50.06  61.0
11  2011-12-31                  11.29  ...                  50.00  58.0
12  2012-12-31                  11.30  ...                  49.13  60.0
13  2013-12-31                  11.25  ...                  49.12  61.0
14  2014-12-31                  11.28  ...                  49.12  60.0
15  2015-12-31                   9.97  ...                  55.29  61.0
16  2016-12-31                   9.97  ...                  55.29  64.0

[17 rows x 921 columns]

In [0]:
import datetime
def datetiem(x):
    date_time_obj = datetime.datetime.strptime(x, '%Y-%m-%d' )
    return date_time_obj

In [0]:
df["Date"] = df["Date"].apply(lambda x: datetiem(x))
df.index = df.Date # index as date because time is not a variable
df=df.drop(['Date'], axis=1)

In [9]:
# df0 = df.fillna(0)
# removes columns where more than 30% of data is missing
# rationale for 0.7, if we can train test split for 0.7/ 0.3 we can accept at least 70% filled data
# fills remaining missing values with the mean of the column   
df_mean = df.loc[:, pd.notnull(df).sum()>len(df)*.80].fillna(df.mean())
# df_mean = df.loc[:, pd.notnull(df).sum()>len(df)*.70].fillna(df.interpolate())
df_mean

ISR_TM_TAX_MANF_BR_ZS  ...   CPI
Date                               ...      
1999-12-31                  13.43  ...  68.0
2000-12-31                  13.43  ...  66.0
2001-12-31                  13.48  ...  76.0
2002-12-31                  11.30  ...  73.0
2003-12-31                  11.27  ...  70.0
2004-12-31                  11.28  ...  64.0
2005-12-31                  11.27  ...  63.0
2006-12-31                  11.26  ...  59.0
2007-12-31                  11.26  ...  61.0
2008-12-31                  11.28  ...  60.0
2009-12-31                  11.29  ...  61.0
2011-12-31                  11.29  ...  58.0
2012-12-31                  11.30  ...  60.0
2013-12-31                  11.25  ...  61.0
2014-12-31                  11.28  ...  60.0
2015-12-31                   9.97  ...  61.0
2016-12-31                   9.97  ...  64.0

[17 rows x 663 columns]

In [0]:
CPI_list = list(df_mean.CPI)
def pct_df(df):
    df.drop(["CPI"], axis=1)
    new_df = df.pct_change()
    new_df.replace(np.nan, 0)
    new_df = new_df.replace([np.inf, -np.inf], 0)
    new_df = new_df.dropna(how='all')
    new_df['CPI']=CPI_list[1:]
    new_df = new_df.fillna(df.mean())
    return new_df
def UpsampleByTimeIndex(df,bytime,method):
    upsampled = df.resample(bytime)
    interpolated = upsampled.interpolate(method=method)
    return interpolated
# Ignore the index and treat the values as equally space
# ‘nearest’, ‘zero’, ‘slinear’, ‘quadratic’, ‘cubic’, ‘spline’, ‘barycentric’, ‘polynomial’
# .agg aggregates/ groups by specified time frame
# D for days, M for months
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html 
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.interpolate.html 
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.resample.Resampler.aggregate.html 
# https://machinelearningmastery.com/resample-interpolate-time-series-data-python/

In [0]:
pct_df_mean = pct_df(df_mean)

In [0]:
#Ignore this code; helper functions for binarizing
# list_col_names = list(pct_df_mean.columns.values)
from itertools import repeat
def binarize(x):
    if x< 0:
        x = -1
    elif x>0:
        x=1
    else:
        x = 0
    return x
month_cpi = [x for item in CPI_list[1:len(CPI_list)-1] for x in repeat(item, 12)]
month_cpi.insert(len(a),CPI_list[len(CPI_list)-1])
def bin_action_cpi(df):
    df.drop(["CPI"], axis=1)
    df = df.applymap(binarize)
    try:
        df['CPI']=CPI_list[1:]
    except:
        df['CPI']= month_cpi
    return df
def bin_action(df):
    df = df.applymap(binarize)
    return df
def binarize10(x):
    if x<= 0:
        x = 0
    else:
        x = 1
    return x
def bin_action_cpi10(df):
    df.drop(["CPI"], axis=1)
    df = df.applymap(binarize10)
    try:
        df['CPI']=CPI_list[1:]
    except:
        df['CPI']= month_cpi
    return df
def bin_action10(df):
    df = df.applymap(binarize10)
    return df
def binarize123(x):
    if x< 0:
        x = 1
    elif x>0:
        x=3
    else:
        x = 2
    return x
def bin_action_cpi123(df):
    df.drop(["CPI"], axis=1)
    df = df.applymap(binarize123)
    try:
        df['CPI']=CPI_list[1:]
    except:
        df['CPI']= month_cpi
    return df
def bin_action123(df):
    df = df.applymap(binarize123)
    return df

In [0]:
# percentage change df and binarize 123
# df_mean_wo_cpi = pct_df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
# df_latest = UpsampleByTimeIndex(pct_df_mean,'Y','linear')
# df_latest = bin_action_cpi123(df_latest)
# df_latest.index = list(range(len(df_latest)))
# df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'Y','linear')
# df_latest_wo_cpi = bin_action123(df_latest_wo_cpi)
# df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

# percentage change df and binarize 0,1
# df_mean_wo_cpi = pct_df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
# df_latest = UpsampleByTimeIndex(pct_df_mean,'M','linear')
# df_latest = bin_action_cpi10(df_latest)
# df_latest.index = list(range(len(df_latest)))
# df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'M','linear')
# df_latest_wo_cpi = bin_action10(df_latest_wo_cpi)
# df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

# percentage change df and binarize -1,0,1
# df_mean_wo_cpi = pct_df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
# df_latest = UpsampleByTimeIndex(pct_df_mean,'Y','linear')
# df_latest = bin_action_cpi(df_latest)
# df_latest.index = list(range(len(df_latest)))
# df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'Y','linear')
# df_latest_wo_cpi = bin_action(df_latest_wo_cpi)
# df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

# percentage change df
df_mean_wo_cpi = pct_df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
df_latest = UpsampleByTimeIndex(pct_df_mean,'M','linear')
df_latest.index = list(range(len(df_latest)))
df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'M','linear')
df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

# mean df
# df_mean_wo_cpi = df_mean.drop(["CPI"], axis=1) # remove cpi to create array of test data
# df_latest = UpsampleByTimeIndex(df_mean,'Y','linear')
# df_latest.index = list(range(len(df_latest)))
# df_latest_wo_cpi = UpsampleByTimeIndex(df_mean_wo_cpi,'Y','linear')
# df_latest_wo_cpi.index = list(range(len(df_latest_wo_cpi)))

In [13]:
df_latest_wo_cpi

ISR_TM_TAX_MANF_BR_ZS  ...  ISR_TM_TAX_TCOM_BR_ZS
0                 0.000000  ...               0.000000
1                 0.000310  ...              -0.000017
2                 0.000621  ...              -0.000033
3                 0.000931  ...              -0.000050
4                 0.001241  ...              -0.000067
..                     ...  ...                    ...
188              -0.038712  ...               0.041870
189              -0.029034  ...               0.031403
190              -0.019356  ...               0.020935
191              -0.009678  ...               0.010468
192               0.000000  ...               0.000000

[193 rows x 662 columns]

In [14]:
# check for null, if false then no missing values
def null_check(dfr):
    return dfr.isnull().values.any()
# print(null_check(df0))
# print(null_check(df_mean))
print(null_check(df_latest_wo_cpi))

False


In [15]:
from sklearn.preprocessing import MinMaxScaler
sc= MinMaxScaler(feature_range=(0,1))

input_data = df_latest.values
test_data = df_latest_wo_cpi.values
input_data[:,0:len(input_data[0])-1] = sc.fit_transform(input_data[:,0:len(input_data[0])-1])
test_data[:,0:len(test_data[0])] = sc.fit_transform(test_data[:,:])
test_data

array([[0.97749688, 0.62751181, 0.80185419, ..., 0.85158643, 0.69649685,
        0.12166918],
       [0.97937214, 0.62873899, 0.80323911, ..., 0.85158643, 0.63922169,
        0.12155256],
       [0.9812474 , 0.62996616, 0.80462402, ..., 0.85158643, 0.58194653,
        0.12143595],
       ...,
       [0.86050392, 0.62667623, 0.73177015, ..., 0.79773484, 0.38274072,
        0.26805765],
       [0.9190004 , 0.62709402, 0.73548489, ..., 0.82466063, 0.39089977,
        0.19486341],
       [0.97749688, 0.62751181, 0.73919963, ..., 0.85158643, 0.39905882,
        0.12166918]])

In [16]:
print(test_data.shape)
print(input_data.shape) # check data and shape, are there 22/ 229 rows?

(193, 662)
(193, 663)


In [17]:
df_latest.head()

ISR_TM_TAX_MANF_BR_ZS  ...        CPI
0               0.977497  ...  66.000000
1               0.979372  ...  66.833333
2               0.981247  ...  67.666667
3               0.983123  ...  68.500000
4               0.984998  ...  69.333333

[5 rows x 663 columns]

In [19]:
n_steps = 3
df_test=test_data[-n_steps:]
CPI_test = df_latest['CPI'][-n_steps:]
print(CPI_test)
print(df_test.shape)
input_feature = input_data[:len(input_data)-n_steps] # to remove last 5 rows, follow the time step you set

190    63.50
191    63.75
192    64.00
Name: CPI, dtype: float64
(3, 662)


In [20]:
input_feature.shape # check shape 

(190, 663)

In [0]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [22]:
# choose a number of time steps
from numpy import array
# convert into input/output
X, y = split_sequences(input_feature, n_steps)
print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])
# the array is (Total number of samples, time step, total number of dimensions)

(188, 3, 662) (188,)
[[0.97749688 0.62751181 0.80185419 ... 0.85158643 0.69649685 0.12166918]
 [0.97937214 0.62873899 0.80323911 ... 0.85158643 0.63922169 0.12155256]
 [0.9812474  0.62996616 0.80462402 ... 0.85158643 0.58194653 0.12143595]] 67.66666666666667
[[0.97937214 0.62873899 0.80323911 ... 0.85158643 0.63922169 0.12155256]
 [0.9812474  0.62996616 0.80462402 ... 0.85158643 0.58194653 0.12143595]
 [0.98312266 0.63119334 0.80600893 ... 0.85158643 0.52467137 0.12131934]] 68.5
[[0.9812474  0.62996616 0.80462402 ... 0.85158643 0.58194653 0.12143595]
 [0.98312266 0.63119334 0.80600893 ... 0.85158643 0.52467137 0.12131934]
 [0.98499792 0.63242052 0.80739385 ... 0.85158643 0.4673962  0.12120273]] 69.33333333333333
[[0.98312266 0.63119334 0.80600893 ... 0.85158643 0.52467137 0.12131934]
 [0.98499792 0.63242052 0.80739385 ... 0.85158643 0.4673962  0.12120273]
 [0.98687318 0.63364769 0.80877876 ... 0.85158643 0.41012104 0.12108612]] 70.16666666666667
[[0.98499792 0.63242052 0.80739385 ... 0

In [23]:
# final model
# https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/ 
# refer to this if necessary
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
model = Sequential()
model.add(LSTM(75, activation='relu', input_shape=(n_steps, X.shape[2])))
model.add(Dense(15))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# model.save_weights('my_model_weights.h5')

Using TensorFlow backend.


In [24]:
# fit model
model.fit(X, y, epochs=200, verbose=0)#, validation_split=0.2, batch_size=5)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where










In [0]:
# demonstrate prediction
x_input = df_test
x_input = x_input.reshape((1, n_steps,X.shape[2] ))
yhat = model.predict(x_input, verbose=0)

Percentage Error

In [26]:
print(yhat)
actual = CPI_test[len(df_latest)-1]
print(float((abs(actual-yhat)/actual)*100))

[[64.11757]]
0.1837015151977539


In [27]:
weight_tensors = model.layers[1].weights
weight_names = list(map(lambda x: x.name, weight_tensors))
print(weight_names)

['dense_1/kernel:0', 'dense_1/bias:0']


In [28]:
for layer in model.layers:
        if "LSTM" in str(layer):
            weightLSTM = layer.get_weights()
warr,uarr, barr = weightLSTM
print(warr.shape) # warr is a numpy array of weights for inputs
print(uarr.shape) # uarr is a numpy array of weights for hidden units
print(barr.shape) # barr is a numpy array of bias

(662, 300)
(75, 300)
(300,)


In [29]:
print(warr)
print(uarr)
print(barr)

[[ 0.07012057 -0.06335633  0.0359504  ...  0.08020607  0.0062677
   0.09002765]
 [-0.04778994 -0.01383412  0.02498766 ... -0.04969701  0.05096054
   0.08433254]
 [-0.05270842 -0.07622582 -0.07143743 ...  0.03624085 -0.05663345
   0.06516201]
 ...
 [ 0.01686111 -0.03424168 -0.01182953 ...  0.08287866  0.05577856
   0.04908691]
 [ 0.01304785  0.03902033  0.03800482 ... -0.03828614  0.02034367
  -0.02387229]
 [ 0.08308981 -0.01035748  0.05303033 ... -0.02054707  0.06425335
   0.05678686]]
[[ 0.03278714 -0.01863568  0.00600876 ...  0.11719739 -0.06404472
   0.0542938 ]
 [-0.00505089  0.11117744  0.04114025 ... -0.1373352  -0.05849872
   0.04638517]
 [ 0.06346167 -0.08154555  0.00836413 ... -0.04769276  0.01588806
  -0.05959089]
 ...
 [ 0.06867906  0.02104246 -0.08039384 ...  0.03915113 -0.0378398
  -0.01930517]
 [ 0.06888973  0.07093787 -0.01846262 ...  0.0541907  -0.17388041
  -0.0506287 ]
 [ 0.11402974  0.12861237 -0.00527957 ...  0.08538972  0.0500888
   0.02509863]]
[ 1.52205313e-02 -7

In [0]:
# change df to percentage changes
# play with the rank/ totaln
# interpolate lesser 
# time step

In [0]:
time step = 5, CPI, indicator data
interpolate by year, 22 data points
# 20.441774368286133
interpolate by month, 262 DP
# 1.0591048002243042
interpolate by day, 7920 DP
# 0.015229816548526287 

After performing percentage change and normalizing 
interpolate by year time step 7
# 0.6501209735870361
# 351430.6875
interpolate by year time step 5
# 0.5464288592338562
# 320606.21875
interpolate by year time step 3
# 1.6997615098953247
interpolate by month time step 7
# 1.4450266361236572
interpolate by month time step 5
# 0.217756450176239


*** champion ***
interpolate by month time step 3
# 0.4332916736602783 25 units
# 0.15020249783992767 50 units 0.24396678805351257
# 0.08212704956531525 75 units
# 0.025785423815250397 75 units dense 15 , 1
# 0.09989678114652634 75 units dense 25 , 1
***  winner  # 0.016958503052592278 75 units dense 35 , 1 
*** end ***


binarize -1,0,1
year time step = 7
# 63.047935485839844
year time step = 5
# 59.16572189331055
year time step = 3
# 82.13848114013672
month time step = 7
# 11.621817588806152
month time step = 5
# 11.747268676757812
month time step = 3
# 15.268765449523926


binarize 0,1
year time step = 7
# 1.3483071327209473
year time step = 5
# 2.037656784057617
year time step = 3
# 4.179565906524658
month time step = 7
# 0.44504478573799133
month time step = 5
# 4.9152421951293945
month time step = 3
# 3.9173173904418945

binarize 1,2,3
year time step = 7
# 5.180117607116699
year time step = 5
# 4.566781520843506
year time step = 3
# 1.8392828702926636
month time step = 7
# 3.652085065841675
month time step = 5
# 4.432069778442383
month time step = 3
# 0.7650640606880188